import LocalizedStrings from 'react-native-localization';

const strings = new LocalizedStrings({
  'en-US': {
    Home: 'Home',
    SaveList: 'Save List',
    Profile: 'Profile',
    Filter: 'Filter',
    PriceRange: 'Price Range',
    LandSize: 'Land Size',
    PropertyType: 'Property Type',
    Bedrooms: 'Bedrooms',
    Bathrooms: 'Bathrooms',
    offer: 'Property at a discount',
    buttonsType: ['ALL', 'RENT', 'BUY'],
    ALL: 'ALL',
    Country: 'Country',
    City: 'City',
    More: 'More Properties',
    search: 'Search',
    EditProfile: 'EditProfile',
    My_shared_Ads: 'My shared Ads',
    Contact_US: 'Contact US',
    Commission: 'Commission',
    Sign_Out: 'Sign Out',
    Terms: 'Terms of Services Privacy Policy',
    Register: 'Register',
    First_Name: 'First Name',
    Last_Name: 'Last Name',
    UserName: 'UserName',
    Email: 'Email',
    Password: 'Password',
    Already: 'Already have an account?',
    Sign_in: 'Sign in',
    Mail_or_User_Name: 'Mail or User Name',
    Login: 'Login',
    Dont_have: 'Don’t have account?',
    Information: ' Edit Profile Information',
    phoneNumbAddresser: 'PhoneNumber',
    Address: 'Address',
    Zi_Code: 'Zip Code',
    VAT_Code: 'VAT Code',
    Edit: 'Edit',
    Reated_Posts: 'Related Posts',
    Property_Feature: 'Property Feature',
    Padding: 'Pending',
    Creditor: 'Creditor',
    Paid: 'Paid',
    Edit_Profile_Information: 'Edit Profile Information',
    shareAds: 'Share Ads',
    Possible_commission: 'Possible commission',
    Desceription: 'Description',
    anyPrice: 'Any Price',
    AnySize: 'Any Size',
    Low: 'Price: Low ...',
    High: 'Price: High ..',
    Date: 'Date',
    PROPERTY: 'PROPERTY',
    PRICE: 'PRICE',
    COMMISSION: 'COMMISSION',
    lan: 'en',
    Settings: 'Settings',
    Push_notification: 'Push notification',
    APP_SETTING: 'APP SETTING',
    Touch_ID_sign_in: 'Touch ID sign in',
    Second_Item: 'Second Item',
    Haptic_feedback_for_tab_events: 'Haptic feedback for tab events',
    Touch_vibration: 'Touch vibration',
    Save_to_Image_gallery: 'Save to Image gallery',
    Image_Resolution: 'Image Resolution',
    Use_the_option_to_usage: 'Use the option "Low" to Lower your data usage',
    Language: 'Language',
    No: 'No',
    Yes: 'No',
    LowS: 'Low',
    HighS: 'High',
    NOTIFICATIONS_SETTINGS: 'NOTIFICATIONS SETTINGS',
    OTHER: 'OTHER',
    Version: 'Version',
  },
  en: {
    Home: 'Home',
    SaveList: 'Save List',
    Profile: 'Profile',
    Filter: 'Filter',
    PriceRange: 'Price Range',
    LandSize: 'Land Size',
    PropertyType: 'Property Type',
    Bedrooms: 'Bedrooms',
    Bathrooms: 'Bathrooms',
    offer: 'Property at a discount',
    buttonsType: ['ALL', 'RENT', 'BUY'],
    ALL: 'ALL',
    Country: 'Country',
    City: 'City',
    More: 'More Properties',
    search: 'Search',
    EditProfile: 'EditProfile',
    My_shared_Ads: 'My shared Ads',
    Contact_US: 'Contact US',
    Commission: 'Commission',
    Sign_Out: 'Sign Out',
    Terms: 'Terms of Services Privacy Policy',
    Register: 'Register',
    First_Name: 'First Name',
    Last_Name: 'Last Name',
    UserName: 'UserName',
    Email: 'Email',
    Password: 'Password',
    Already: 'Already have an account?',
    Sign_in: 'Sign in',
    Mail_or_User_Name: 'Mail or User Name',
    Login: 'Login',
    Dont_have: 'Don’t have account?',
    Information: ' Edit Profile Information',
    phoneNumbAddresser: 'PhoneNumber',
    Address: 'Address',
    Zi_Code: 'Zip Code',
    VAT_Code: 'VAT Code',
    Edit: 'Edit',
    Reated_Posts: 'Related Posts',
    Property_Feature: 'Property Feature',
    Padding: 'Pending',
    Creditor: 'Creditor',
    Paid: 'Paid',
    Edit_Profile_Information: 'Edit Profile Information',
    shareAds: 'Share Ads',
    Possible_commission: 'Possible commission',
    Desceription: 'Description',
    anyPrice: 'Any Price',
    AnySize: 'Any Size',
    Low: 'Price: Low ...',
    High: 'Price: High ..',
    Date: 'Date',
    PROPERTY: 'PROPERTY',
    PRICE: 'PRICE',
    COMMISSION: 'COMMISSION',
    lan: 'en',
    Settings: 'Settings',
    Push_notification: 'Push notification',
    APP_SETTING: 'APP SETTING',
    Touch_ID_sign_in: 'Touch ID sign in',
    Second_Item: 'Second Item',
    Haptic_feedback_for_tab_events: 'Haptic feedback for tab events',
    Touch_vibration: 'Touch vibration',
    Save_to_Image_gallery: 'Save to Image gallery',
    Image_Resolution: 'Image Resolution',
    Use_the_option_to_usage: 'Use the option "Low" to Lower your data usage',
    Language: 'Language',
    No: 'No',
    Yes: 'No',
    LowS: 'Low',
    HighS: 'High',
    NOTIFICATIONS_SETTINGS: 'NOTIFICATIONS SETTINGS',
    OTHER: 'OTHER',
    Version: 'Version',
  },
  hu: {
    Home: 'Otthon',
    SaveList: 'Lista mentése',
    Profile: 'Profil',
    Filter: 'Szűrő',
    PriceRange: 'Ártartomány',
    LandSize: 'Földméret',
    PropertyType: 'Ingatlan Típusa',
    Bedrooms: 'Hálószobák',
    Bathrooms: 'Fürdőszobák',
    offer: 'Ingatlan kedvezményes áron',
    buttonsType: ['MINDEN', 'BÉRLÉS', 'MEGVESZ'],
    ALL: 'MINDEN',
    Country: 'Ország',
    City: 'Város',
    More: 'További Tulajdonságok',
    search: 'Keresés',
    EditProfile: 'Profil Szerkesztése',
    My_shared_Ads: 'Saját megosztott hirdetéseim',
    Contact_US: 'Lépjen kapcsolatba velünk',
    Commission: 'jutalék',
    Sign_Out: 'Kijelentkezés',
    Terms: 'Szolgáltatási feltételek adatvédelmi irányelve',
    Register: 'Regisztráció',
    First_Name: 'Keresztnév',
    Last_Name: 'Vezetéknév',
    UserName: 'Felhasználónév',
    Email: 'Email',
    Password: 'Jelszó',
    Already: 'Már van fiókja?',
    Sign_in: 'Bejelentkezés',
    Mail_or_User_Name: 'E-mail vagy felhasználónév',
    Login: 'Bejelentkezés',
    Dont_have: 'Nincs számlád?',
    Information: ' Profilinformációk szerkesztése',
    phoneNumbAddresser: 'Telefonszám',
    Address: 'Cím',
    Zi_Code: 'Irányítószám',
    VAT_Code: 'VAT Code',
    Edit: 'Szerkesztés',
    Reated_Posts: 'Kapcsolódó hozzászólások',
    Property_Feature: 'Property Feature',
    Padding: 'Folyamatban',
    Creditor: 'Hitelező',
    Paid: 'Fizetett',
    Edit_Profile_Information: 'Profilinformációk szerkesztése',
    shareAds: 'Hirdetések megosztása',
    Possible_commission: 'Lehetséges jutalék',
    Desceription: 'Jellemzők',
    anyPrice: 'Bármely ár',
    AnySize: 'Bármely méret',
    Low: 'Ár: Alacsony ...',
    High: 'Ár: Magas ..',
    Date: 'Dátum',
    PROPERTY: 'tulajdon',
    PRICE: 'ár',
    COMMISSION: 'Bizottság',
    lan: 'hu',
    Settings: 'Beállítások',
    Push_notification: 'Azonnali értesítés',
    APP_SETTING: 'APP BEÁLLÍTÁS',
    Touch_ID_sign_in: 'Touch ID sign in',
    Second_Item: 'Második tétel',
    Haptic_feedback_for_tab_events: 'Haptikus visszajelzés a fül eseményeiről',
    Touch_vibration: 'Érintse meg a rezgést',
    Save_to_Image_gallery: 'Mentés a képgalériába',
    Image_Resolution: 'Képfelbontás',
    Use_the_option_to_usage:
      'Az "Alacsony" opcióval csökkentheti adatfelhasználását',
    Language: 'Nyelv',
    No: 'Nem',
    Yes: 'Igen',
    LowS: 'Alacsony',
    HighS: 'Magas',
    NOTIFICATIONS_SETTINGS: 'BEJELENTÉSEK BEÁLLÍTÁSOK',
    OTHER: 'EGYÉB',
    Version: 'Változat',
  },
  de: {
    Home: 'Zuhause',
    SaveList: 'Liste speichern',
    Profile: 'Profile',
    Filter: 'Filter',
    PriceRange: 'Preisklasse',
    LandSize: 'Landgröße',
    PropertyType: 'Art der Immobilie',
    Bedrooms: 'Schlafzimmer',
    Bathrooms: 'Badezimmer',
    offer: 'Eigentum mit einem Rabatt',
    buttonsType: ['ALLE', 'MIETE', 'KAUFEN'],
    ALL: 'ALLE',
    Country: 'Land',
    City: 'Stadt',
    More: 'Weitere Eigenschaften',
    search: 'Suche',
    EditProfile: 'Profil Bearbeiten',
    My_shared_Ads: 'Meine geteilten Anzeigen',
    Contact_US: 'Kontaktiere uns',
    Commission: 'Kommission',
    Sign_Out: 'Ausloggen',
    Terms: 'Nutzungsbedingungen Datenschutzbestimmungen',
    Register: 'Registrieren',
    First_Name: 'Vorname',
    Last_Name: 'Nachname',
    UserName: 'Registrieren',
    Email: 'Email',
    Password: 'Passwort',
    Already: 'Sie haben bereits ein Konto?',
    Sign_in: 'Einloggen',
    Mail_or_User_Name: 'Mail oder Benutzername',
    Login: 'Anmeldung',
    Dont_have: 'Sie haben noch keinen Account?',
    Information: ' Profilinformationen bearbeiten',
    phoneNumbAddresser: 'Telefonnummer',
    Address: 'Adresse',
    Zi_Code: 'Postleitzahl',
    VAT_Code: 'VAT Code',
    Edit: 'Bearbeiten',
    Reated_Posts: 'zusammenhängende Posts',
    Property_Feature: 'Eigenschaften',
    Padding: 'Steht aus',
    Creditor: 'Gläubiger',
    Paid: 'Bezahlt',
    Edit_Profile_Information: 'Profilinformationen bearbeiten',
    shareAds: 'Anzeigen teilen',
    Possible_commission: 'Mögliche Provision',
    Desceription: 'Beschreibung',
    anyPrice: 'Jeder Preis',
    AnySize: 'Alle Größen',
    Low: 'Preis: Niedrig ...',
    High: 'Preis: Hoch ..',
    Date: 'Datum',
    PROPERTY: 'EIGENTUM',
    PRPRICEEIS: 'PREIS',
    COMMISSION: 'KOMMISSION',
    lan: 'de',
    Settings: 'die Einstellungen',
    Push_notification: 'Sofortige Benachrichtigung',
    APP_SETTING: 'APP SETUP',
    Touch_ID_sign_in: 'Touch ID sign in',
    Second_Item: 'Zweiter Satz',
    Haptic_feedback_for_tab_events: 'Haptisches Feedback zu Ohrereignissen',
    Touch_vibration: 'Berühre die Vibration',
    Save_to_Image_gallery: 'Mentés a képgalériába',
    Image_Resolution: 'In der Bildergalerie speichern',
    Use_the_option_to_usage:
      'Verwenden Sie die Option "Niedrig", um die Datennutzung zu reduzieren',
    Language: 'Sprache',
    No: 'Nein',
    Yes: 'Ja',
    LowS: 'Niedrig',
    HighS: 'groß',
    NOTIFICATIONS_SETTINGS: 'BENACHRICHTIGUNGSEINSTELLUNGEN',
    OTHER: 'ANDERE',
    Version: 'Ausführung',
  },
});



export default strings
